import React from "react";
import { 
  X, 
  Printer, 
  Download, 
  FileText, 
  Shield, 
  Lock, 
  Calendar, 
  User, 
  Building2, 
  Hash, 
  CheckCircle2, 
  MapPin,
  Flag
} from "lucide-react";
import { CaseDossier } from "../types";
import { downloadTextFile } from "../utils/crypto";

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  caseData: CaseDossier;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  caseData
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleExportMarkdown = () => {
    const md = `# ${caseData.classification} // INVESTIGATIVE DOSSIER
**CASE ID**: ${caseData.caseId}  
**TITLE**: ${caseData.title}  
**TARGET SUBJECT**: ${caseData.targetSubject || "Unspecified"}  
**LEAD INVESTIGATOR**: ${caseData.leadInvestigator} (${caseData.agencyOrganization})  
**DATE GENERATED**: ${new Date().toUTCString()}  

---

## 1. EXECUTIVE OVERVIEW & NOTES
${caseData.notes || "No general investigator field notes recorded."}

---

## 2. CROSS-PLATFORM IDENTITY VERIFICATION
${caseData.scans.map(s => `
### Target: @${s.target_username}
- Scanned At: ${s.scanned_at}
- Found Platforms: ${s.found_count} / ${s.total_platforms}
- Identity Correlation Score: ${s.correlation_score}%
- Verified Accounts:
${s.platforms.filter(p => p.status === "FOUND").map(p => `  * [${p.name}](${p.url}) (${p.category}) - Latency: ${p.latency_ms}ms`).join("\n")}
`).join("\n")}

---

## 3. FORENSIC PHOTO & METADATA LEDGER
${caseData.analyzedPhotos.map(ph => `
### Photo: ${ph.filename}
- SHA-256 Hash: \`${ph.hashes.sha256}\`
- Camera: ${ph.camera_profile.make} ${ph.camera_profile.model}
- Lens: ${ph.camera_profile.lens}
- Capture Time: ${ph.camera_profile.datetime_original}
- GPS Coordinates: ${ph.gps_coordinates ? `${ph.gps_coordinates.latitude}, ${ph.gps_coordinates.longitude} (${ph.gps_coordinates.google_maps_url})` : "None Embedded"}
- Tampering Flags: ${ph.tamper_indicators.length > 0 ? ph.tamper_indicators.join(", ") : "None Detected"}
`).join("\n")}

---

## 4. EVIDENCE VAULT & CHAIN OF CUSTODY
${caseData.evidence.map(e => `
- **${e.title}** [${e.category}]
  * Timestamp: ${e.timestamp}
  * Cryptographic Hash: \`${e.hash || "N/A"}\`
  * Details: ${e.details}
  ${e.investigatorNotes ? `* Notes: ${e.investigatorNotes}` : ""}
`).join("\n")}

---

## 5. AI INTELLIGENCE BRIEFING
${caseData.aiBriefing?.summary || "No AI briefing generated."}

---
*Generated by AEGIS.OSINT Forensic Suite - Zero Knowledge Encrypted Environment*
`;

    downloadTextFile(md, `${caseData.caseId}_Forensic_Dossier.md`, "text/markdown");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm overflow-y-auto">
      <div className="bg-[#0F1115] border border-[#1F2937] rounded-lg w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Top Control Bar */}
        <div className="p-4 bg-[#0A0A0C] border-b border-[#1F2937] flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-400" />
            <h2 className="text-sm font-bold font-mono text-white uppercase tracking-wide">
              Official Investigative Dossier & Forensic Report
            </h2>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleExportMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-[#1A1D24] hover:bg-[#1F2937] text-slate-200 border border-[#2D333F] text-xs font-mono transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export .MD</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-blue-600 hover:bg-blue-500 text-white text-xs font-mono transition-colors shadow-[0_0_12px_rgba(37,99,235,0.35)]"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Dossier</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-md hover:bg-[#1A1D24] text-slate-400 hover:text-white transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Printable Report Canvas */}
        <div id="printable-report-area" className="p-8 overflow-y-auto space-y-6 text-slate-200 font-mono text-xs bg-[#0A0A0C]">
          {/* Classification Banner */}
          <div className="text-center py-2 px-4 rounded-md border border-rose-500/40 bg-rose-500/10 text-rose-300 font-bold uppercase tracking-widest text-sm">
            {caseData.classification} // FOR OFFICIAL USE ONLY
          </div>

          {/* Dossier Header Metadata */}
          <div className="border border-[#1F2937] rounded-lg p-5 bg-[#13161C] space-y-4">
            <div className="flex flex-col sm:flex-row justify-between items-start gap-4 border-b border-[#1F2937] pb-4">
              <div>
                <span className="text-[10px] text-blue-400 font-bold tracking-widest block uppercase">
                  CONFIDENTIAL INTELLIGENCE DOSSIER
                </span>
                <h1 className="text-lg font-bold text-white mt-0.5">{caseData.title}</h1>
                <p className="text-xs text-slate-400 mt-1">
                  Target Subject: <strong className="text-white font-semibold">{caseData.targetSubject || "Unassigned"}</strong>
                </p>
              </div>

              <div className="text-right sm:text-right text-xs space-y-1">
                <div className="text-slate-400">
                  Case ID: <span className="font-bold text-white font-mono">{caseData.caseId}</span>
                </div>
                <div className="text-slate-400">
                  Status: <span className="text-emerald-400 font-bold">{caseData.status}</span>
                </div>
                <div className="text-[11px] text-slate-500">
                  Date: {new Date().toLocaleDateString()}
                </div>
              </div>
            </div>

            {/* Investigator Identity Block */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs pt-1">
              <div>
                <span className="text-[10px] text-slate-500 block uppercase">Lead Investigator</span>
                <span className="font-medium text-slate-200">{caseData.leadInvestigator}</span>
              </div>
              <div>
                <span className="text-[10px] text-slate-500 block uppercase">Agency / Org</span>
                <span className="font-medium text-slate-200">{caseData.agencyOrganization}</span>
              </div>
              <div>
                <span className="text-[10px] text-slate-500 block uppercase">Encryption Standard</span>
                <span className="text-blue-400 font-medium">AES-256-GCM (PBKDF2)</span>
              </div>
              <div>
                <span className="text-[10px] text-slate-500 block uppercase">Total Artifacts</span>
                <span className="text-emerald-400 font-medium">{caseData.evidence.length} Vaulted</span>
              </div>
            </div>
          </div>

          {/* Section 1: Executive Findings */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-blue-400 uppercase tracking-wide border-b border-[#1F2937] pb-1">
              1.0 Executive Case Notes
            </h3>
            <p className="text-slate-300 leading-relaxed bg-[#0F1115] p-4 rounded-md border border-[#1F2937] whitespace-pre-wrap">
              {caseData.notes || "Case created in secure environment. Evidence compilation underway."}
            </p>
          </div>

          {/* Section 2: Identity Correlation Matrix */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-blue-400 uppercase tracking-wide border-b border-[#1F2937] pb-1">
              2.0 Cross-Platform Identity Verification Results
            </h3>
            {caseData.scans.length > 0 ? (
              caseData.scans.map((scan, i) => (
                <div key={i} className="bg-[#0F1115] rounded-md p-3 border border-[#1F2937] space-y-2">
                  <div className="flex justify-between items-center text-xs">
                    <span>
                      Target: <strong>@{scan.target_username}</strong>
                    </span>
                    <span className="text-blue-400">
                      Correlation Score: <strong>{scan.correlation_score}%</strong> ({scan.found_count} verified)
                    </span>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 pt-1">
                    {scan.platforms.filter(p => p.status === "FOUND").map(p => (
                      <div key={p.id} className="flex items-center justify-between p-1.5 rounded bg-[#0A0A0C] border border-[#1F2937] text-[11px]">
                        <span className="text-slate-200">{p.name} ({p.category})</span>
                        <a href={p.url} target="_blank" rel="noreferrer" className="text-blue-400 truncate max-w-[180px]">
                          {p.url}
                        </a>
                      </div>
                    ))}
                  </div>
                </div>
              ))
            ) : (
              <p className="text-slate-500 italic">No identity scans recorded for this dossier.</p>
            )}
          </div>

          {/* Section 3: Forensic Photo Metadata */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-blue-400 uppercase tracking-wide border-b border-[#1F2937] pb-1">
              3.0 Digital Photo Forensic Analysis & Optics
            </h3>
            {caseData.analyzedPhotos.length > 0 ? (
              <div className="space-y-3">
                {caseData.analyzedPhotos.map((photo, i) => (
                  <div key={i} className="bg-[#0F1115] rounded-md p-3 border border-[#1F2937] space-y-2">
                    <div className="flex justify-between text-xs">
                      <span className="font-semibold text-white">{photo.filename}</span>
                      <span className="text-blue-400 font-medium">{photo.camera_profile.make} {photo.camera_profile.model}</span>
                    </div>
                    <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-[11px] text-slate-400">
                      <div>Timestamp: <span className="text-slate-200">{photo.camera_profile.datetime_original}</span></div>
                      <div>GPS: <span className="text-emerald-400">{photo.gps_coordinates ? `${photo.gps_coordinates.latitude}, ${photo.gps_coordinates.longitude}` : "None"}</span></div>
                      <div>Lens: <span className="text-slate-200">{photo.camera_profile.lens}</span></div>
                    </div>
                    <div className="text-[10px] text-slate-500 font-mono break-all">
                      SHA-256: {photo.hashes.sha256}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-slate-500 italic">No photos ingested into forensic ledger.</p>
            )}
          </div>

          {/* Section 4: Vaulted Evidence Ledger */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-blue-400 uppercase tracking-wide border-b border-[#1F2937] pb-1">
              4.0 Vaulted Evidence & Chain of Custody Ledger
            </h3>
            {caseData.evidence.length > 0 ? (
              <table className="w-full text-left text-[11px] border border-[#1F2937] rounded-md">
                <thead>
                  <tr className="bg-[#13161C] text-slate-400 border-b border-[#1F2937]">
                    <th className="p-2">ARTIFACT TITLE</th>
                    <th className="p-2">CATEGORY</th>
                    <th className="p-2">RECORDED AT</th>
                    <th className="p-2">HASH / INTEGRITY</th>
                  </tr>
                </thead>
                <tbody>
                  {caseData.evidence.map((item) => (
                    <tr key={item.id} className="border-b border-[#1F2937]/50 hover:bg-[#13161C]">
                      <td className="p-2 font-medium text-slate-200">{item.title}</td>
                      <td className="p-2 text-slate-400">{item.category}</td>
                      <td className="p-2 text-slate-500">{new Date(item.timestamp).toLocaleString()}</td>
                      <td className="p-2 text-blue-400 font-mono truncate max-w-[120px]">
                        {item.hash ? item.hash.substring(0, 16) + "..." : "VERIFIED"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <p className="text-slate-500 italic">Evidence vault is empty.</p>
            )}
          </div>

          {/* Section 5: AI Intelligence Briefing */}
          {caseData.aiBriefing && (
            <div className="space-y-2">
              <h3 className="text-xs font-bold text-blue-400 uppercase tracking-wide border-b border-[#1F2937] pb-1">
                5.0 AI Intelligence Synthesizer Briefing
              </h3>
              <div className="bg-[#0F1115] p-4 rounded-md border border-[#1F2937] leading-relaxed whitespace-pre-wrap text-slate-300">
                {caseData.aiBriefing.summary}
              </div>
            </div>
          )}

          {/* Investigator Sign-Off Block */}
          <div className="pt-6 border-t border-[#1F2937] grid grid-cols-2 gap-8 text-xs">
            <div className="space-y-4">
              <div className="border-b border-[#2D333F] pb-1">
                <span className="text-[10px] text-slate-500 uppercase">Investigator Signature</span>
                <p className="font-mono text-blue-400 font-bold">{caseData.leadInvestigator}</p>
              </div>
              <span className="text-[10px] text-slate-500">Date: {new Date().toLocaleDateString()}</span>
            </div>

            <div className="space-y-4 text-right">
              <div className="border-b border-[#2D333F] pb-1">
                <span className="text-[10px] text-slate-500 uppercase">Security Clearance Stamp</span>
                <p className="font-mono text-emerald-400 font-bold">DIGITALLY HASHED & VERIFIED</p>
              </div>
              <span className="text-[10px] text-slate-500">Suite: AEGIS.OSINT v3.4 PRO</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
